#!/bin/bash
clear
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
clear
echo -e "\E[44;1;37m    INSTALAR O PAINEL ONEVPS v1.1    \E[0m" 
echo ""
echo -ne "\n\033[1;32mDEFINA UMA SENHA PARA O\033[1;33m MYSQL\033[1;37m: "; read senha
echo -e "\n\033[1;36mINICIANDO INSTALACAO \033[1;33mAGUARDE..."
apt-get update -y > /dev/null 2>&1
apt-get install cron curl unzip -y > /dev/null 2>&1
echo -e "\n\033[1;36mINSTALANDO O APACHE2 \033[1;33mAGUARDE...\033[0m"
apt-get install apache2 -y > /dev/null 2>&1
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
echo -e "\n\033[1;36mINSTALANDO O MySQL \033[1;33mAGUARDE...\033[0m"
echo "debconf mysql-server/root_password password $senha" | debconf-set-selections
echo "debconf mysql-server/root_password_again password $senha" | debconf-set-selections
apt-get install mysql-server -y > /dev/null 2>&1
mysql_install_db > /dev/null 2>&1
(echo $senha; echo n; echo y; echo y; echo y; echo y)|mysql_secure_installation > /dev/null 2>&1
echo -e "\n\033[1;36mINSTALANDO O PHPMYADMIN \033[1;33mAGUARDE...\033[0m"
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $senha" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $senha" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $senha" | debconf-set-selections
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
apt-get install phpmyadmin -y > /dev/null 2>&1
php5enmod mcrypt > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y > /dev/null 2>&1
if [ "$(php -m |grep ssh2)" = "ssh2" ]; then
  true
else
  clear
  echo -e "\033[1;31m ERRO CRITICO,TENTE INSTALAR NO UBUNTU 14 OU DERIVADOS\033[0m"
  rm $HOME/install.sh
  exit
fi
apt-get install php5-curl > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
clear
echo ""
echo -e "\033[1;31m ATENCAO \033[1;33m!!!"
echo ""
echo -ne "\033[1;32m INFORME A MESMA SENHA\033[1;37m: "; read senha
sleep 1
mysql -h localhost -u root -p$senha -e "CREATE DATABASE sshplus"
mysql -h localhost -u root -p$senha -e "CREATE DATABASE ssh"
clear
echo -e "\033[1;36m FINALIZANDO INSTALACAO\033[0m"
echo ""
echo -e "\033[1;33m AGUARDE..."
echo ""

cd /var/www/html
wget https://raw.githubusercontent.com/lucianolima2905/Painel-site/main/onepainel.zip > /dev/null 2>&1
unzip onepainel.zip > /dev/null 2>&1
rm -rf onepainel.zip index.html > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1
sleep 1
if [[ -e "/var/www/html/pages/system/pass.php" ]]; then
sed -i "s;1010;$senha;g" /var/www/html/pages/system/pass.php > /dev/null 2>&1
sed -i "s;1010;$senha;g" /var/www/html/site/pages/system/pass.php > /dev/null 2>&1
fi
sleep 1
cd
wget https://raw.githubusercontent.com/lucianolima2905/Painel-site/main/banco.sql > /dev/null 2>&1
wget https://raw.githubusercontent.com/lucianolima2905/Painel-site/main/banco2.sql > /dev/null 2>&1
sleep 1
if [[ -e "$HOME/banco.sql" ]]; then
    mysql -h localhost -u root -p$senha --default_character_set utf8 sshplus < banco.sql
	mysql -h localhost -u root -p$senha --default_character_set utf8 ssh < banco2.sql
    rm /root/banco.sql
	rm /root/banco2.sql
else
    clear
    echo -e "\033[1;31m ERRO AO IMPORTAR BANCO DE DADOS\033[0m"
    sleep 2
    rm /root/install.sh > /dev/null 2>&1
    exit
fi
service apache2 restart > /dev/null 2>&1
clear
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.ssh.php ' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.sms.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.online.ssh.php' >> /etc/crontab
echo '10 * * * * root /usr/bin/php /var/www/html/pages/system/cron.servidor.php' >> /etc/crontab
echo '*/30 * * * * root /usr/bin/php /var/www/html/pages/system/cron.limpeza.php' >> /etc/crontab

echo '* * * * * root /usr/bin/php /var/www/html/site/pages/system/cron.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/site/pages/system/cron.ssh.php ' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/site/pages/system/cron.sms.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/site/pages/system/cron.online.ssh.php' >> /etc/crontab
echo '10 * * * * root /usr/bin/php /var/www/html/site/pages/system/cron.servidor.php' >> /etc/crontab
echo '*/30 * * * * root /usr/bin/php /var/www/html/site/pages/system/cron.limpeza.php' >> /etc/crontab
wget https://raw.githubusercontent.com/lucianolima2905/Painel-site/main/html.sh > /dev/null 2>&1 && chmod 777 html.sh && sed -i -e 's/\r$//' html.sh && ./html.sh
/etc/init.d/cron reload > /dev/null 2>&1
/etc/init.d/cron restart > /dev/null 2>&1
chmod 777 /var/www/html/admin/pages/servidor/ovpn
chmod 777 /var/www/html/admin/pages/download
chmod 777 /var/www/html/admin/pages/faturas/comprovantes
service apache2 restart > /dev/null 2>&1
clear
echo -e "\033[1;32m PAINEL ONEVPS v1.1 INSTALADO COM SUCESSO!"
echo -e "\033[1;32m Em caso de erros entra na pasta LEIAME em /var/www/html"
echo -e "\033[1;32m OBS:Na VPS Cliente SSH PAGO usar o script SSH PLUS OU CRASHVPN"
echo -e "\033[1;32m Na VPS Cliente SSH FREE usar o script SSH PLUS OU CRASHVPN junto com o VPSMANAGERSETUP para evitar erros na criação de contas FREE"
echo -e "\033[1;32m Use o script de sicronização em todas as VPS (Painel e Cliente SSH) após a instalação"
echo ""
echo -e "\033[1;36m SEU PAINEL:\033[1;37m http://$IP/\033[0m"
echo -e "\033[1;36m USUARIO:\033[1;37m admin\033[0m"
echo -e "\033[1;36m SENHA:\033[1;37m admin\033[0m"
echo -e "\033[1;36m CASO NAO ENTRE BASTA COLOCAR UM /admin NA BARRA DE ENDERECO"
echo ""
echo -e "\033[1;32m MODDED BY @ANDLEY302!"
echo ""
echo -e "\033[1;33m Altere a senha quando logar no painel>> Configuracoes>> Senha Antiga: admin >> Nova Senha: \033[0m"
cat /dev/null > ~/.bash_history && history -c
rm /root/install
